### ISSUE TITLE
TypeError: Object function (req, res, next)

### ISSUE THREAD

**Issue by GAMEBOOK** [FGRibreau/forever-webui#27]
Caught exception: TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'

I have this error when I launch : "sudo npm start"

I don't understand how to fix my problem.

**Comment by dafunkk** [comment]
same problem here, got it with npm install and sudo node app.js

**Comment by FGRibreau** [comment]
I think the issue is related is a not backward-compatible update of express. I will happily accept a PR for this @GAMEBOOK @dafunkk
